# Generated by Django 2.0.2 on 2019-01-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gatepass',
            fields=[
                ('gatepassid', models.IntegerField(db_column='gatepassId', primary_key=True, serialize=False)),
                ('studentid', models.CharField(blank=True, db_column='studentId', max_length=10, null=True)),
                ('place', models.CharField(blank=True, max_length=20, null=True)),
                ('sdate', models.DateField(blank=True, null=True)),
                ('ddate', models.DateField(blank=True, null=True)),
                ('cheak', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'gatepass',
                'managed': False,
            },
        ),
    ]
