# Generated by Django 2.1.7 on 2019-02-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_gatepass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('itemid', models.IntegerField(primary_key=True, serialize=False)),
                ('itemname', models.CharField(blank=True, max_length=45, null=True)),
                ('itemprice', models.IntegerField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'canteen',
                'managed': False,
            },
        ),
    ]
