# Generated by Django 2.1.7 on 2019-02-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_complain1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complain1',
            options={},
        ),
    ]
