# Generated by Django 2.1.7 on 2019-02-27 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20190226_2253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complain1',
        ),
    ]
